# Generated by Django 5.1.5 on 2025-02-14 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_tweetcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TweetComment',
        ),
    ]
